FROM umihico/aws-lambda-selenium-python:latest

WORKDIR ${LAMBDA_TASK_ROOT}

RUN pip install --no-cache-dir poetry

COPY pyproject.toml poetry.lock ${LAMBDA_TASK_ROOT}/
RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-root --only=main

COPY app ${LAMBDA_TASK_ROOT}/app
COPY lambda_handler.py ${LAMBDA_TASK_ROOT}/

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=${LAMBDA_TASK_ROOT}

CMD [ "lambda_handler.lambda_handler" ]
