name: 'Deploy to AWS Lambda'
description: 'Deploy scraper service to AWS Lambda using Serverless Framework'
inputs:
  stage:
    description: 'Deployment stage'
    required: true
  region:
    description: 'AWS region'
    required: false
    default: 'us-east-1'
  api-version:
    description: 'API version'
    required: true
  cors-origins:
    description: 'CORS origins (JSON array)'
    required: false
    default: '["*"]'
  tor-browser-path:
    description: 'Tor Browser path (Lambda Layer path)'
    required: false
    default: ''
  tor-data-dir:
    description: 'Tor Browser data directory'
    required: false
    default: ''
  database-url:
    description: 'MySQL database connection URL'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: ðŸ“¦ Install Serverless plugins
      shell: bash
      run: |
        npm install

    - name: ðŸ³ Build and push Docker image to ECR
      shell: bash
      env:
        AWS_REGION: ${{ inputs.region }}
      run: |
        echo "ðŸ³ Building Docker image..."
        docker build -f docker/Dockerfile.lambda -t indexoffy-api:${{ inputs.stage }} .

        echo "ðŸ” Getting AWS account ID..."
        AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        ECR_REPOSITORY_NAME="indexoffy-api"
        ECR_REPOSITORY_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${ECR_REPOSITORY_NAME}"

        echo "ðŸ“¦ Creating ECR repository if it doesn't exist..."
        aws ecr describe-repositories --repository-names ${ECR_REPOSITORY_NAME} --region ${{ inputs.region }} 2>/dev/null || \
        aws ecr create-repository --repository-name ${ECR_REPOSITORY_NAME} --region ${{ inputs.region }} --image-scanning-configuration scanOnPush=true

        echo "ðŸ” Logging in to Amazon ECR..."
        aws ecr get-login-password --region ${{ inputs.region }} | docker login --username AWS --password-stdin ${ECR_REPOSITORY_URI}

        echo "ðŸ“¤ Pushing image to ECR..."
        IMAGE_TAG="${{ inputs.stage }}-${{ inputs.region }}"
        docker tag indexoffy-api:${{ inputs.stage }} ${ECR_REPOSITORY_URI}:${IMAGE_TAG}
        docker push ${ECR_REPOSITORY_URI}:${IMAGE_TAG}

        echo "ECR_REPOSITORY_URI=${ECR_REPOSITORY_URI}" >> $GITHUB_ENV
        echo "âœ… Image pushed: ${ECR_REPOSITORY_URI}:${IMAGE_TAG}"

    - name: ðŸš€ Deploy to AWS Lambda
      shell: bash
      env:
        API_VERSION: ${{ inputs.api-version }}
        CORS_ORIGINS: ${{ inputs.cors-origins }}
        TOR_BROWSER_PATH: ${{ inputs.tor-browser-path }}
        TOR_DATA_DIR: ${{ inputs.tor-data-dir }}
        DATABASE_URL: ${{ inputs.database-url }}
        ECR_REPOSITORY_URI: ${{ env.ECR_REPOSITORY_URI }}
      run: |
        echo "ðŸš€ Deploying to AWS Lambda..."
        echo "Stage: ${{ inputs.stage }}"
        echo "Region: ${{ inputs.region }}"
        echo "API Version: ${{ inputs.api-version }}"

        serverless deploy \
          --stage ${{ inputs.stage }} \
          --region ${{ inputs.region }} \
          --verbose
